config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  authenticated :user do
    root 'users#index', as: :authenticated_root
  end

  root 'home#homepage'

  get "/languages" => "language_choices#new"
  post "/languages" => "language_choices#create"
  get "/languages/edit" => "language_choices#edit"
  patch "/languages" => "language_choices#udpate"
  put "/languages" => "language_choices#udpate"

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  resources :conversations do
    resources :messages
  end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
	belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, scope: :recipient_id

	scope :involving, -> (user) do 
	  where("conversations.sender_id =? OR conversations.recipient_id =?", user.id, user.id)
	end

	scope :between, -> (sender_id, recipient_id) do
	  where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id, recipient_id, recipient_id, sender_id)
	end
end

app/models/desired.rb
class Desired < ActiveRecord::Base
	belongs_to :user
	belongs_to :language
end

app/models/language.rb
class Language < ActiveRecord::Base
	has_many :native_speakers, through: :native_languages, source: :natives
	has_many :desired_speakers, through: :desired_languages, source: :desireds
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id
end

app/models/native.rb
class Native < ActiveRecord::Base
	belongs_to :user
	belongs_to :language
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :natives
  has_many :native_languages, through: :natives, source: :language

  has_many :desireds
  has_many :desired_languages, through: :desireds, source: :language

  has_many :conversations, foreign_key: :sender_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!

  def create
	@conversation = find_conversation
	if @conversation.save
	  redirect_to conversation_path(@conversation.id)
	else 
	  redirect_to root_path, alert: "There was an issue"
	end
  end

  def show
	@conversation = Conversation.find(params[:id])
	@receiver = interlocutor(@conversation)
	@messages = @conversation.messages
	@message = Message.new
	desired_languages = current_user.desired_languages
	native_languages = current_user.native_languages
	@users = User.where(id: Native.select(:user_id).where(language: desired_languages)).where(id: Desired.select(:user_id).where(language: native_languages))
	@conversations = Conversation.involving(current_user)
  end

  private

  def find_conversation
	current_user.conversations.find_or_initialize_by(recipient_id: params[:recipient_id])
  end

  def interlocutor(conversation)
	current_user == conversation.recipient ? conversation.sender : conversation.recipient
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!
  
  def homepage
  end
end

app/controllers/language_choices_controller.rb
class LanguageChoicesController < ApplicationController
  # include ActiveModel::Model
  # attr_accessor :native_id, :desired_id
  
  def new
    @languages = Language.all
  	@user = current_user.id
  	@natives = Native.find_by(language_id: params[:language_id])
  	@desireds = Desired.find_by(language_id: params[:language_id])
  end

  def create
  	natives = params[:natives]
  	desireds = params[:desireds]
  	for d in desireds
  	  current_user.desired_languages.push(Language.find(d))
  	end  	

  	for n in natives
  	  current_user.native_languages.push(Language.find(d))
  	end
    redirect_to root_path, notice: "Welcome! Now you can start chatting with matched users."
  end

  def edit
  	@languages = Language.all
  	@user = current_user.id
  	@natives = Native.find_by(language_id: params[:language_id])
  	@desireds = Desired.find_by(language_id: params[:language_id])
  end

  def update
  	@natives.update(params[:natives])
  	@desireds.update(params[:desireds])
  	redirect_to root_path, notice: "Languages successfully updated"
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_filter :authenticate_user!
	
	def create
	  @conversation = Conversation.find(params[:conversation_id])
	  @message = @conversation.messages.build(message_params)
	  @message.user_id = current_user.id
	  @message.save!

	  @path = conversation_path(@conversation)
	end

	private
	def message_params
	  params.require(:message).permit(:body)
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_sign_up_path_for(resource)
    '/languages'
  end

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
	  @users = matched
    @conversations = Conversation.involving(current_user)
  end

  private
  def matched
    desired_languages = current_user.desired_languages
    native_languages = current_user.native_languages
    User.where(id: Native.select(:user_id).where(language: desired_languages)).where(id: Desired.select(:user_id).where(language: native_languages))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def resource_name
	  :user
    end

	def resource
      @resource ||= User.new
	end

	def devise_mapping
	  @devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper

  def message_interlocutor(message)
    message.user == message.conversation.sender ? message.conversation.sender : message.conversation.recipient
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def conversation_interlocutor(conversation)
    conversation.recipient == current_user ? conversation.sender : conversation.recipient
  end
end

app/views/conversations/_show.html.erb
<div class="chat-container">
    <div class="chat-box-title">
      <div class="title-text"><%= @receiver.name %></div>
    </div>
  <div class="chat-window">
    <div class="message-container">
    <% if @messages.any? %>
        <%= render @messages %>
    <% end %>
    </div>
    <div class="input-container">
      <%= form_for([@conversation, @message], :remote => true, :html => { id: "conversation_form_#{@conversation.id}"}) do |f| %>
      <div class="inner-wrapper">
        <div><%= f.text_area :body, class: "textbox", "data-cid" => @conversation.id %></div>
        <div><%= f.submit "SEND", class: "send-btn"%></div>
        <div class="clear"></div>
      </div>
    </div>
      <% end %>
</div>

<%= subscribe_to conversation_path(@conversation) %>

app/views/conversations/show.html.erb
<div class="page-container">
  <div class="dashboard">
    <%= render '/users/matches' %>
    <%= render '/users/previous' %>
  </div>
  <div class="chat-container">
      <div class="chat-box-title">
        <div class="title-text"><%= @receiver.name %></div>
      </div>
    <div class="chat-window">
      <div class="message-container">
      <% if @messages.any? %>
          <%= render @messages %>
      <% end %>
      </div>
      <div class="input-container">
        <%= form_for([@conversation, @message], :remote => true, :html => { id: "conversation_form_#{@conversation.id}"}) do |f| %>
        <div class="inner-wrapper">
          <div><%= f.text_area :body, class: "textbox", "data-cid" => @conversation.id %></div>
          <div><%= f.submit "SEND", class: "send-btn"%></div>
          <div class="clear"></div>
        </div>
      </div>
        <% end %>
  </div>
  <%= subscribe_to conversation_path(@conversation) %>
</div>
<div class="clear"></div>

<script>
    $(".message-container").scrollTop(function() { return this.scrollHeight; });
    $('.textbox').keydown(function(event){    
        if(event.keyCode==13){
            $('.send-btn').submit();
            $('.textbox').val("");
        }
    });
</script> 

app/views/home/_sign_in_modal.html.erb
<div id="sign-in" class="modal">
    <div class="modal-content">
      <h4>Sign In</h4>
      <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password, autocomplete: "off" %>
      </div>
      <% if devise_mapping.rememberable? -%>
        <div class="field">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
        </div>
      <% end -%>
        <div class="submit-btn">
          <%= f.submit "Sign In" %>
        </div>
        <div class="modal-footer">
        <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Close</a>
        </div>
      <% end %>
      <%= render "devise/shared/links" %>
    </div>
</div>

app/views/home/_sign_up_modal.html.erb
<div id="sign-up" class="modal">
    <div class="modal-content">
      <h4>Sign Up</h4>
      <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <%= devise_error_messages! %>
      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true %>
      </div>
      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true %>
      </div>
      <div class="field">
        <%= f.label :password %>
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "off" %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "off" %>
      </div>
      <div class="submit-btn">
        <%= f.submit "Sign up" %>
      </div>
      <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Close</a>
      </div>
    <% end %>
    <%= render "devise/shared/links" %>
    </div>
</div>

app/views/home/homepage.html.erb
<div class="hero-module">
    <div class="hero-text-wrapper">
        <h1>Language exchanges <br>made easy.</h1>
        <p>Squillo is a tool for those who are hungry to learn new languages. Instantly connect with native speakers across the globe and chat in real-time.</p>
    </div>
</div>
<div id="info-section">
    <div class="down"><a href="/#info-section"><i class="fa fa-chevron-circle-down fa-4x"></a></i></div>
    <h1>Get Started in 3 Easy Steps:</h1>
    <div class="box-container">
        <div class="info-box">
            <div class="icon"><i class="fa fa-pencil-square-o fa-5x"></i></div>
            <h3>Sign Up</h3>
            <p>Create an account <%= link_to '<a class="modal-trigger" href="#sign-up">here</a>'.html_safe, new_user_registration_path %> with just your name, email, and password.</p>
        </div>
        <div class="info-box">
            <div class="icon"><i class="fa fa-globe fa-5x"></i></div>
            <h3>Set your language preferences</h3>
            <p>Choose the language(s) that you speak at a native level as well as the languages you'd like to practice.
        </div>
        <div class="info-box">
            <div class="icon"><i class="fa fa-users fa-5x"></i></div>
            <h3>Connect with your matches</h3>
            <p>On your dashboard click the "Send Message" button next to any matched user to start chatting instantly. That's it!</p>
        </div>
    </div>
</div>
<div class="footer">
    <p>&copy;2016 Squillo</p>
</div>
<%= render "sign_up_modal" %>
<%= render "sign_in_modal" %>

app/views/language_choices/_form.html.erb
<div class="edit-container">
	<%= form_tag languages_path, method: :post do %>
	<h3>What are your native languages?</h3>
		<div class="input-field col s12">
		    <select multiple>
		      	<option value="" disabled selected>Choose your language</option>
				<% for language in @languages %>
				  <option value="1"><%= select_tag "natives[]", language.id%><%= label_tag language.name%></option>
			</select>
<!-- 			<label>Materialize Multiple Select</label> -->
		</div>
		<%end %>
	<h3>What languages are you are learning?</h3>
	<% for language in @languages %>
		<%= check_box_tag "desireds[]", language.id%>
		<%= label_tag language.name%>
	<%end %>
	  <%= submit_tag "Submit" %>
</div>
<% end %>

app/views/language_choices/edit.html.erb
<div class="edit-container">
	<h3>Edit Language Settings</h3>
	<%= form_tag languages_path, method: :put do %>
	<div class="field">
	<h5>What are your native languages?</h5>
	<% for language in @languages %>
		<%= check_box_tag "natives[]", language.id%>
		<%= label_tag language.name%>
	<%end %>
	<h5>What languages are you are learning?</h5>
	<% for language in @languages %>
		<%= check_box_tag "desireds[]", language.id%>
		<%= label_tag language.name%>
	<%end %>
	  <%= submit_tag "Submit" %>
	</div>
	<% end %>
</div>

app/views/language_choices/new.html.erb
<div class="edit-container">
	<h1>Choose Language Preferences</h1>
	<%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
  <title>squillo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="nav">
  <div id="logo"><a href="/">squillo</a></div>
  <ul>
    <% if user_signed_in? %>
    <li id="greeting">Hi, <strong><%= current_user.name %>!</strong></li>
    <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><a href="/#info-section">About</a></li>
    <li><%= link_to '<a class="waves-effect waves-light modal-trigger" href="#sign-up">Sign Up</a>'.html_safe, new_user_registration_path %></li>
    <li><%= link_to '<a class="waves-effect waves-light modal-trigger" href="#sign-in">Sign In</a>'.html_safe, new_user_session_path %></li>
  <% end %>
  </ul>
</div>
	  
<div class="container">
  <% if alert %>
      <div class="alert"><%= alert %></div>
  <% end %>
  <% if notice %>
      <div class="notice"><%= notice %></div>
  <% end %>
  <%= yield %>
</div>
<!-- <audio id="chatAudio"><source src="/sounds/notification.mp3" type="audio/mpeg"></audio> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
</body>
</html>

app/views/messages/_message.html.erb
<div class="chatboxmessagecontent">
    <time datetime="<%= message.created_at %>" title="<%= message.created_at.strftime("%d %b  %Y at %I:%M%p") %>">
      <%= message_interlocutor(message).name %><div class="time"><%= message.created_at.strftime("%I:%M %p") %></div>
    </time>
    <p><%= message.body %></p>
</div>

app/views/messages/create.js.erb
<% publish_to @path do %>

	$(".message-container").append("<%= j render( partial: @message ) %>");
	$(".message-container").scrollTop(function() { return this.scrollHeight; });

<% end %>

app/views/users/_matches.html.erb
<div class="matches-title">
    <div class="title-text">Matched Users</div>
</div>
<div class="matches">
  <% @users.each do |user| %>
    <div class="user-list-wrapper">
      <div class="avatar"><i class="fa fa-user fa-2x"></i></div>
      <div class="username"><%= user.name %></div>
      <div><%= link_to "Send Message", conversations_path(recipient_id: user.id), method: :post, class: "start-chat-btn" %></div>
      <div class="clear"></div>
    </div>
  <% end %>
</div>

app/views/users/_previous.html.erb
<div class="previous-chats-title">
  <div class="title-text">Previous Chats</div>
</div>
<div class="chatlist">
  <% if @conversations.any? %>
    <% @conversations.each do |conversation| %>
    <div class="user-list-wrapper">
      <div class="avatar"><i class="fa fa-user fa-2x"></i></div>
      <div class="username"><%= conversation_interlocutor(conversation).name %></div>
      <div><%= link_to "Open Chat", conversation_path(conversation), class: "start-chat-btn", "data-cid" => conversation.id %></div>
      <div class="clear"></div>
    </div>
  <% end %>
  <% else %>
    <p>No conversations yet. Send a message to any matched user to start chatting!</p>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="page-container">
	<div class="dashboard">
	  <%= render 'matches' %>
	  <%= render 'previous' %>
	</div>
</div>